///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class JournalDetailsData {
/*
{
  "_id": "685beb6058526db7c0418615",
  "title": "Grateful for a calm morning",
  "description": "Had a peaceful start to the day with meditation and journaling.",
  "emotion": "Peaceful",
  "feelings": "Calm, Focused",
  "activities": "Meditation, Journaling",
  "createdAt": "2025-06-25T12:28:16.488Z",
  "updatedAt": "2025-06-25T12:28:16.488Z"
}
*/

  String? Id;
  String? title;
  String? description;
  String? emotion;
  String? feelings;
  String? activities;
  String? createdAt;
  String? updatedAt;

  JournalDetailsData({
    this.Id,
    this.title,
    this.description,
    this.emotion,
    this.feelings,
    this.activities,
    this.createdAt,
    this.updatedAt,
  });
  JournalDetailsData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
    emotion = json['emotion']?.toString();
    feelings = json['feelings']?.toString();
    activities = json['activities']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['description'] = description;
    data['emotion'] = emotion;
    data['feelings'] = feelings;
    data['activities'] = activities;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class JournalDetails {
/*
{
  "status": true,
  "message": "Journal entry fetched successfully",
  "data": {
    "_id": "685beb6058526db7c0418615",
    "title": "Grateful for a calm morning",
    "description": "Had a peaceful start to the day with meditation and journaling.",
    "emotion": "Peaceful",
    "feelings": "Calm, Focused",
    "activities": "Meditation, Journaling",
    "createdAt": "2025-06-25T12:28:16.488Z",
    "updatedAt": "2025-06-25T12:28:16.488Z"
  }
}
*/

  bool? status;
  String? message;
  JournalDetailsData? data;

  JournalDetails({
    this.status,
    this.message,
    this.data,
  });
  JournalDetails.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? JournalDetailsData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
