part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const AUTH_DIRECTION = _Paths.AUTH_DIRECTION;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const GET_STARTED = _Paths.GET_STARTED;
  static const LOGIN = _Paths.LOGIN;
  static const ONBOARDING_QUESTIONS = _Paths.ONBOARDING_QUESTIONS;
  static const CREATE_AVATAR = _Paths.CREATE_AVATAR;
  static const AVATAR_NAME = _Paths.AVATAR_NAME;
  static const NAVIGATION_BAR = _Paths.NAVIGATION_BAR;
  static const PROFILE = _Paths.PROFILE;
  static const SETTINGS = _Paths.SETTINGS;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const MOOD_SELECTION_FORM = _Paths.MOOD_SELECTION_FORM;
  static const MENTAL_GYM = _Paths.MENTAL_GYM;
  static const WORKOUT_DETAILS = _Paths.WORKOUT_DETAILS;
  static const COURSE_COMPLETE = _Paths.COURSE_COMPLETE;
  static const QUIZE_COMPLETE = _Paths.QUIZE_COMPLETE;
  static const COMMUNITY = _Paths.COMMUNITY;
  static const CREATE_COMMUNITY = _Paths.CREATE_COMMUNITY;
  static const COMMUNITY_POSTS = _Paths.COMMUNITY_POSTS;
  static const CREATE_POST = _Paths.CREATE_POST;
  static const COMMENT_BOTTOM_SHEET = _Paths.COMMENT_BOTTOM_SHEET;
  static const ACTIVITIES = _Paths.ACTIVITIES;
  static const SUPPORT = _Paths.SUPPORT;
  static const CHALLENGES = _Paths.CHALLENGES;
  static const CHALLENGE_DETAILS = _Paths.CHALLENGE_DETAILS;
  static const JOURNALING = _Paths.JOURNALING;
  static const CREATE_TIME_LINE = _Paths.CREATE_TIME_LINE;
  static const MIND_FULL_HOURS = _Paths.MIND_FULL_HOURS;
  static const GET_SCHOOL = _Paths.GET_SCHOOL;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const QUIZE_COLLECT_COIN = _Paths.QUIZE_COLLECT_COIN;
  static const SEARCH_MENTAL_GYM = _Paths.SEARCH_MENTAL_GYM;
  static const UPDATE_TIMELINE = _Paths.UPDATE_TIMELINE;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const AUTH_DIRECTION = '/auth-direction';
  static const SIGN_UP = '/sign-up';
  static const GET_STARTED = '/get-started';
  static const LOGIN = '/login';
  static const ONBOARDING_QUESTIONS = '/onboarding-questions';
  static const CREATE_AVATAR = '/create-avatar';
  static const AVATAR_NAME = '/avatar-name';
  static const NAVIGATION_BAR = '/navigation-bar';
  static const PROFILE = '/profile';
  static const SETTINGS = '/settings';
  static const EDIT_PROFILE = '/edit-profile';
  static const MOOD_SELECTION_FORM = '/mood-selection-form';
  static const MENTAL_GYM = '/mental-gym';
  static const WORKOUT_DETAILS = '/workout-details';
  static const COURSE_COMPLETE = '/course-complete';
  static const QUIZE_COMPLETE = '/quize-complete';
  static const COMMUNITY = '/community';
  static const CREATE_COMMUNITY = '/create-community';
  static const COMMUNITY_POSTS = '/community-posts';
  static const CREATE_POST = '/create-post';
  static const COMMENT_BOTTOM_SHEET = '/comment-bottom-sheet';
  static const ACTIVITIES = '/activities';
  static const SUPPORT = '/support';
  static const CHALLENGES = '/challenges';
  static const CHALLENGE_DETAILS = '/challenge-details';
  static const JOURNALING = '/journaling';
  static const CREATE_TIME_LINE = '/create-time-line';
  static const MIND_FULL_HOURS = '/mind-full-hours';
  static const GET_SCHOOL = '/get-school';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const QUIZE_COLLECT_COIN = '/quize-collect-coin';
  static const SEARCH_MENTAL_GYM = '/search-mental-gym';
  static const UPDATE_TIMELINE = '/update-timeline';
}
